#!/bin/bash
filename=./file
# &&|| 条件判断表达式
#判断文件是否存在
#目录
#读权限
#写权限
#执行权限
test -f $filename && echo "exist" || echo "not exist"
test -d $filename && echo "exist" || echo "not exist"
test -r $filename && echo "exist" || echo "not exist"
test -w $filename && echo "exist" || echo "not exist"
test -x $filename && echo "exist" || echo "not exist"
#
#
#
#
